import type { NextPage } from 'next'
import React from 'react'
import Head from 'next/head'
import HeroSection from './components/HeroSection'
import Experience from './components/Experience'
import Skills from './components/Skills'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title >Paulo de Assis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
      <HeroSection /> 
      <Experience />
      <Skills />
    </div>
  )
}

export default Home
