import type { NextPage } from 'next'
import React from 'react'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import HeroSection from './components/HeroSection'
import Experience from './components/Experience'

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Paulo de Assis</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.svg" />
      </Head>
    <HeroSection /> 
    <Experience />
    </div>
  )
}

export default Home
